### ISSUE TITLE
大佬，你这个接口是用什么app啊，影视好像不行。

### ISSUE THREAD

**Issue by forkman24** [eklins/FDTV#1]

**Comment by eklins** [comment]
FreeDTV，然后输入自建接口接口，接口模式：https://github.com/eklins/FDTV/raw/main/tv/
如要清洁版，使用以下接口，因为这个很多时候用来测试。
https://github.com/eklins/FreeD/raw/master/tv/
软件只能谷歌下载，playstore没有此软件。

**Comment by eklins** [comment]
已回复问题

**Comment by forkman24** [comment]
好的，明白了。多谢大佬指点
